### PR TITLE
Removed logger

### PR DESCRIPTION
**Pull request by andrewwatson**
Removed logger completely for #3 due to compatibility with Google App Engine

### CODE REVIEW

**Comment by kevinburke** [comment]
@andrewwatson - can you paste the exact error you're getting from the logger? Let's see if we can't fix this to compile correctly.

**Comment by kevinburke** [comment]
I'm also OK with removing the log messages there, but would rather delete them than comment them out.

**Comment by andrewwatson** [comment]
good call on the removal vs. commenting out.  i got in a hurry and committed too quickly 😄

**Comment by andrewwatson** [comment]
the error was this 
``` 
2017/02/06 13:55:36 go-app-builder: Failed parsing input: parser: bad import "syscall" in github.com/inconshreveable/log15/term/terminal_appengine.go from GOPATH
```

**Comment by kevinburke** [comment]
Hmm here's the source code I have for that file

```
// Based on ssh/terminal:
// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build appengine

package term

// IsTty always returns false on AppEngine.
func IsTty(fd uintptr) bool {
	return false
}
```

**Comment by kevinburke** [comment]
Are you sure you have an up to date version of log15?

**Comment by andrewwatson** [comment]
Yeah, I have the same content for that file.  It's something about the way it builds the app that hides the real problem

**Comment by andrewwatson** [comment]
so, i think it's not enough to // +build appengine on terminal_appengine.go 

I think it might only work to do // -build appengine on the others that use syscall...  that's a thing, right?

**Comment by kevinburke** [comment]
Yes, I've been looking at it. It would be helpful to run with `go build -x` and see which files are included in the final build. This is difficult since `GOOS=appengine go build -x` raises a compile time error.

The other files shouldn't be included because of their use of `_arch.go` suffixes which only compile for the given architecture.

**Comment by andrewwatson** [comment]
ok, so this makes it compile...

```
GOOS=appengine /Users/andy/utils/go_appengine/goroot/bin/go-app-builder -app_base /Users/andy/go/src/github.com/andrewwatson/investor-conferencing -arch 6 -dynamic -goroot /Users/andy/utils/go_appengine/goroot -nobuild_files ^^$ -unsafe -gopath /Users/andy/go -print_extras_hash twiml.go types.go calls.go main.go dashboard.go splash.go recording.go api.go
``` 
without changing log15 code at all but then i run the 
```
goapp serve
``` 
command to develop locally it doesn't set GOOS!

**Comment by kevinburke** [comment]
Huh. I can't tell what you changed there... :(


--
Kevin Burke
925.271.7005 | kev.inburke.com

**Comment by kevinburke** [comment]
Gonna go ahead and close this as we fixed it a different way.

**Pull request closed without merging**
